#!/usr/bin/env python3
"""Bundle the whole repository into one self-contained Markdown file.

    python scripts/make_bundle.py                    # -> dist/ARCHIVER_BUNDLE.md
    python scripts/make_bundle.py ~/ARCHIVER_BUNDLE.md   # or an explicit path

The output is designed to be handed to another AI agent (or a human) who then
recreates the repository from scratch: it carries the file tree, a SHA-256 for
every file so nothing gets silently truncated, and the complete contents of each
file in a code fence long enough to survive nested backticks.

Only files tracked by git are included, so the memory bank (*.db) and anything
gitignored can never leak into a bundle.
"""

from __future__ import annotations

import hashlib
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "dist" / "ARCHIVER_BUNDLE.md"

HEADER = """<!--
  ARCHIVER — single-file repository bundle
  Generated by scripts/make_bundle.py. Do not edit by hand.

  INSTRUCTIONS FOR AN AI AGENT OR HUMAN READING THIS FILE:

  1. Create a new GitHub repository named exactly: Archiver
  2. Recreate every file listed under "File manifest" at the exact path shown,
     with byte-identical contents taken from its code block in "File contents".
  3. Check each file against the SHA-256 in the manifest. If one does not match,
     you truncated or altered it — redo that file.
  4. The fences use a variable number of backticks because some files contain
     triple-backtick blocks. Strip only the outer fence, never inner ones.
  5. Files ending in a newline must keep it. `run.sh`, `publish.sh` and the
     Makefile matter; keep their executable bits (chmod +x run.sh publish.sh).
  6. Do NOT create archiver.db — it is the user's private memory bank and is
     deliberately absent. The app creates it on first run.
  7. Then: see "Publish commands" at the end of this file.
-->
"""


def sh(*args: str) -> str:
    return subprocess.run(
        args, cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout


def fence_for(text: str) -> str:
    """A fence longer than any backtick run inside the content."""
    longest, run = 0, 0
    for ch in text:
        run = run + 1 if ch == "`" else 0
        longest = max(longest, run)
    return "`" * max(4, longest + 1)


def main() -> int:
    files = sh("git", "ls-files").split()
    if not files:
        print("no tracked files", file=sys.stderr)
        return 1

    blobs: dict[str, tuple[str, str]] = {}
    for rel in files:
        text = (ROOT / rel).read_text()
        digest = hashlib.sha256(text.encode()).hexdigest()
        blobs[rel] = (text, digest)

    commit = sh("git", "rev-parse", "--short", "HEAD").strip()
    log = sh("git", "log", "--pretty=format:%h %s", "-n", "20").strip()
    total_bytes = sum(len(t.encode()) for t, _ in blobs.values())
    total_lines = sum(t.count("\n") + 1 for t, _ in blobs.values())

    out: list[str] = [HEADER]
    out.append(f"""
# Archiver — repository bundle

| | |
| --- | --- |
| **Repository name** | `Archiver` |
| **Description** | An LLM chat app that saves memory — one SQLite file you own. |
| **Default branch** | `main` |
| **License** | MIT (see `LICENSE`) |
| **Topics** | `llm`, `memory`, `rag`, `sqlite`, `fastapi`, `chatgpt`, `grok`, `personal-knowledge` |
| **Visibility** | public (your call) |
| **Generated** | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} from commit `{commit}` |
| **Files** | {len(files)} |
| **Lines** | {total_lines:,} |
| **Bytes** | {total_bytes:,} |

Nothing here is a diff or a summary. Every file is reproduced in full below.

---

## File manifest

Recreate exactly these paths. Relative to the repository root.

| # | Path | Lines | Bytes | SHA-256 | Executable |
| --: | --- | --: | --: | --- | :---: |""")

    for i, rel in enumerate(sorted(files), 1):
        text, digest = blobs[rel]
        exe = "yes" if rel in ("run.sh", "publish.sh") else ""
        out.append(
            f"| {i} | `{rel}` | {text.count(chr(10)) + 1} | "
            f"{len(text.encode()):,} | `{digest}` | {exe} |"
        )

    out.append(f"""
**Totals:** {len(files)} files, {total_lines:,} lines, {total_bytes:,} bytes.

Deliberately absent: `archiver.db` (the user's private memory bank — gitignored,
created automatically on first run), `__pycache__/`, `.venv/`, `.pytest_cache/`,
`dist/`.

---

## File tree

```text
Archiver/
""")
    tree = sorted(files)
    dirs: set[str] = set()
    for rel in tree:
        parts = rel.split("/")
        for i in range(1, len(parts)):
            dirs.add("/" .join(parts[:i]))
    for d in sorted(dirs):
        out.append(f"{d}/")
    for rel in tree:
        out.append(rel)
    out.append("```")

    out.append("""
---

## File contents

Each block below is the complete, byte-exact content of one file. The opening
fence states the target path. Copy everything between the outer fences.

""")

    for rel in sorted(files):
        text, digest = blobs[rel]
        fence = fence_for(text)
        out.append(f"### `{rel}`\n")
        out.append(f"Path: `{rel}` · SHA-256: `{digest}`\n")
        out.append(f"{fence}{rel}")
        out.append(text.rstrip("\n"))
        out.append(fence)
        out.append("")

    out.append(f"""
---

## Publish commands

```bash
git init -b main
git add -A
git commit -m "Archiver: an LLM chat app that saves memory"
chmod +x run.sh publish.sh

# with the GitHub CLI
gh repo create Archiver --public --source=. --remote=origin --push \\
  --description "An LLM chat app that saves memory — one SQLite file you own."

# or by hand (create the empty repo on github.com first)
git remote add origin git@github.com:YOUR_USERNAME/Archiver.git
git push -u origin main
```

### Verify after pushing

```bash
python3 -m venv .venv && . .venv/bin/activate
pip install -r requirements.txt
python -m pytest tests/ -q          # expect: 58 passed
uvicorn app.main:app --host 0.0.0.0 --port 8000
```

---

## Commit history of the source repository

Optional — recreate it if you want the history, ignore it if you only want the
final state.

```
{log}
```

---

*Bundle generated from commit `{commit}`. {len(files)} files, {total_bytes:,} bytes.
Every SHA-256 above is of the exact file content between its fences.*
""")

    out_path = Path(sys.argv[1]).expanduser() if len(sys.argv) > 1 else OUT
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out).lstrip("\n"))
    size = out_path.stat().st_size
    print(f"wrote {out_path} — {size:,} bytes, {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
